source "https://github.com/retro-labs/specs-ios-swift.git"
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '15.0'

target 'TestOOGDebugingKit' do
     pod 'OOGDebugingKit', :path => '../'
end
